import '@fontsource/im-fell-english/400.css'
import '@fontsource/im-fell-english/400-italic.css'
import '@fontsource/im-fell-english-sc/400.css'
import '@fontsource/im-fell-great-primer/400.css'
import '@fontsource/im-fell-great-primer/400-italic.css'
import { useMemo, type MouseEvent, type ReactNode } from 'react'
import type { ThemeProps } from '../../shared/theme-contract'
import type { Project, SiteContent } from '../../content/types'
import { routePath, TOP_LEVEL_ROUTES } from '../../shared/routes'
import {
  bbox,
  fractalLine,
  hachures,
  mulberry32,
  pointInPolygon,
  territory,
  toPath,
  type Pt,
  type Territory,
} from './terrain'
import './atlas.css'

// atlas — the résumé as territory (PLAN Phase 5, direction B "Iron Gall").
// Coastlines are generated by seeded midpoint displacement, so every region
// keeps a stable identity while never being hand-drawn. Composition is authored
// (cartographic layout is design); silhouette is procedural.
//
// This pass renders the full plate. Pan/zoom exploration lands next.

const VB = { w: 1600, h: 1000 }

// Anchors are chosen so land never sits under the cartouche (upper-left water)
// or the legend (lower-right water) — the same discipline the style tiles used.
const MAIN = { cx: 850, cy: 620, rx: 200, ry: 250 }

interface Settlement {
  name: string
  at: Pt
  major: boolean
}

/** Nudge a target until it lands inside the polygon (spiral search). */
function findInside(target: Pt, poly: Pt[], step = 14): Pt {
  if (pointInPolygon(target, poly)) return target
  for (let r = step; r < step * 14; r += step) {
    for (let a = 0; a < 12; a++) {
      const ang = (a / 12) * Math.PI * 2
      const p = { x: target.x + Math.cos(ang) * r, y: target.y + Math.sin(ang) * r }
      if (pointInPolygon(p, poly)) return p
    }
  }
  return target
}

interface Plate {
  main: Territory
  isles: { t: Territory; project: Project; label: Pt }[]
  divider: string
  terra: string
  relief: { x1: number; y1: number; x2: number; y2: number }[]
  regions: { north: Pt; south: Pt }
  settlements: Settlement[]
  routes: string[]
}

function buildPlate(content: SiteContent): Plate {
  const main = territory({ id: 'damyan-hristov', ...MAIN, n: 11, roughness: 0.36 })
  const box = bbox(main.points)
  const rng = mulberry32(20260805)

  const released = content.projects.filter((p) => p.status === 'released')
  const isles = released.map((project, i) => {
    // The archipelago sits in the clear water between the index (above) and the
    // legend (below); alternating longitude keeps neighbouring isles apart.
    // The archipelago works a narrow band of water: the index closes it from
    // above (~y 240) and the legend from below (y 558), and each isle carries a
    // label ~38 below its southern shore. Isles alternate longitude, so the
    // binding constraint is the same-column pair (i, i+2) at 2·dy apart — not
    // the adjacent one. Radius jitter reaches ~1.28×, so ry_max ≈ 41 ≤ dy.
    const t = released.length === 1 ? 0.5 : i / (released.length - 1)
    const cx = 1290 + (i % 2 === 0 ? -95 : 95)
    const cy = 300 + t * 171
    const terr = territory({
      id: project.slug,
      cx,
      cy,
      rx: 58,
      ry: 32,
      n: 8,
      roughness: 0.34,
    })
    const b = bbox(terr.points)
    return { t: terr, project, label: { x: cx, y: b.maxY + 22 } }
  })

  // internal border between the province of study and the province of labour
  const divider = toPath(
    fractalLine(
      { x: box.minX - 30, y: MAIN.cy - 26 },
      { x: box.maxX + 30, y: MAIN.cy + 44 },
      mulberry32(77),
      0.17,
      5,
    ),
    false,
  )

  // the Delft coast: charted from report, never surveyed
  const terra = toPath(
    fractalLine({ x: 632, y: 178 }, { x: 1104, y: 104 }, mulberry32(1312), 0.2, 5),
    false,
  )

  const north = findInside({ x: MAIN.cx, y: MAIN.cy - MAIN.ry * 0.52 }, main.points)
  const south = findInside({ x: MAIN.cx, y: MAIN.cy + MAIN.ry * 0.5 }, main.points)

  const settlements: Settlement[] = [
    { name: 'EINDHOVEN', at: { x: MAIN.cx - 46, y: MAIN.cy - MAIN.ry * 0.74 }, major: true },
    { name: 'SOFIA', at: { x: MAIN.cx + 52, y: MAIN.cy - MAIN.ry * 0.2 }, major: true },
    { name: 'TOTEM', at: { x: MAIN.cx - 34, y: MAIN.cy + MAIN.ry * 0.28 }, major: true },
    { name: 'INDEAVR', at: { x: MAIN.cx + 44, y: MAIN.cy + MAIN.ry * 0.66 }, major: false },
  ].map((s) => ({ ...s, at: findInside(s.at, main.points) }))

  // correlation routes: a language to the work that proves it
  const anchor = { x: box.maxX - 30, y: MAIN.cy + 10 }
  const routes = isles.map((isle) => {
    const b = bbox(isle.t.points)
    const to = { x: b.minX + 10, y: (b.minY + b.maxY) / 2 }
    const midX = (anchor.x + to.x) / 2
    return `M ${anchor.x.toFixed(1)} ${anchor.y.toFixed(1)} C ${midX.toFixed(1)} ${anchor.y.toFixed(1)}, ${midX.toFixed(1)} ${to.y.toFixed(1)}, ${to.x.toFixed(1)} ${to.y.toFixed(1)}`
  })

  return {
    main,
    isles,
    divider,
    terra,
    relief: hachures(main, rng, 34, 17),
    regions: { north, south },
    settlements,
    routes,
  }
}

function Link({
  to,
  navigate,
  className,
  children,
  current,
}: {
  to: string
  navigate: ThemeProps['navigate']
  className?: string
  children: ReactNode
  current?: boolean
}) {
  const onClick = (e: MouseEvent<HTMLAnchorElement>) => {
    e.preventDefault()
    navigate(to)
  }
  return (
    <a
      href={to}
      className={className}
      aria-current={current ? 'page' : undefined}
      onClick={onClick}
    >
      {children}
    </a>
  )
}

export function Root({ content, route, navigate }: ThemeProps) {
  const plate = useMemo(() => buildPlate(content), [content])
  const path = routePath(route)
  const home = route.kind === 'home'

  return (
    <div className="atl">
      <div className="a-plate-wrap">
        <svg
          className="a-plate"
          viewBox={`0 0 ${VB.w} ${VB.h}`}
          preserveAspectRatio="xMidYMid slice"
          aria-hidden="true"
        >
          <defs>
            <filter id="a-rough" x="-6%" y="-6%" width="112%" height="112%">
              <feTurbulence
                type="fractalNoise"
                baseFrequency="0.03"
                numOctaves="4"
                seed="19"
                result="n"
              />
              <feDisplacementMap
                in="SourceGraphic"
                in2="n"
                scale="4"
                xChannelSelector="R"
                yChannelSelector="G"
              />
            </filter>
            <pattern
              id="a-hLight"
              width="9"
              height="9"
              patternUnits="userSpaceOnUse"
              patternTransform="rotate(35)"
            >
              <line
                x1="0"
                y1="0"
                x2="0"
                y2="9"
                stroke="#2c2218"
                strokeWidth="0.55"
                opacity="0.55"
              />
            </pattern>
            <pattern
              id="a-hMed"
              width="5"
              height="5"
              patternUnits="userSpaceOnUse"
              patternTransform="rotate(35)"
            >
              <line x1="0" y1="0" x2="0" y2="5" stroke="#2c2218" strokeWidth="0.55" opacity="0.6" />
            </pattern>
            <pattern
              id="a-hCross"
              width="5"
              height="5"
              patternUnits="userSpaceOnUse"
              patternTransform="rotate(35)"
            >
              <line
                x1="0"
                y1="0"
                x2="0"
                y2="5"
                stroke="#2c2218"
                strokeWidth="0.55"
                opacity="0.62"
              />
              <line
                x1="0"
                y1="0"
                x2="5"
                y2="0"
                stroke="#2c2218"
                strokeWidth="0.55"
                opacity="0.62"
              />
            </pattern>
            <clipPath id="a-clipMain">
              <path d={plate.main.path} />
            </clipPath>
          </defs>

          <g filter="url(#a-rough)">
            {/* coastal shading: successive parallel lines following the shore */}
            <g fill="none" stroke="#2c2218">
              <path d={plate.main.path} strokeWidth="15" opacity="0.05" />
              <path d={plate.main.path} strokeWidth="10" opacity="0.07" />
              <path d={plate.main.path} strokeWidth="5.5" opacity="0.1" />
            </g>
            <path d={plate.main.path} fill="url(#a-hLight)" />
            <path d={plate.main.path} fill="none" stroke="#2c2218" strokeWidth="2.6" />

            <g clipPath="url(#a-clipMain)">
              <path
                d={plate.divider}
                fill="none"
                stroke="#2c2218"
                strokeWidth="1.6"
                strokeDasharray="12 7"
                opacity="0.8"
              />
              <g stroke="#2c2218" strokeWidth="0.9" opacity="0.42">
                {plate.relief.map((h, i) => (
                  <line key={i} x1={h.x1} y1={h.y1} x2={h.x2} y2={h.y2} />
                ))}
              </g>
            </g>

            {plate.isles.map(({ t, project }) => (
              <g key={t.id}>
                <path
                  d={t.path}
                  fill={`url(#${project.category === 'university' ? 'a-hCross' : 'a-hMed'})`}
                />
                <path d={t.path} fill="none" stroke="#2c2218" strokeWidth="2" />
              </g>
            ))}

            <path
              d={plate.terra}
              fill="none"
              stroke="#a5301b"
              strokeWidth="1.8"
              strokeDasharray="14 10"
              opacity="0.85"
            />
          </g>

          <g fill="none" stroke="#a5301b" strokeWidth="1" strokeDasharray="5 7" opacity="0.6">
            {plate.routes.map((d, i) => (
              <path key={i} d={d} />
            ))}
          </g>

          {/* compass: a north marker and a cross, nothing more */}
          <g transform="translate(1000,240)">
            <circle r="40" fill="none" stroke="#2c2218" strokeWidth="0.9" opacity="0.55" />
            <line
              x1="-52"
              y1="0"
              x2="52"
              y2="0"
              stroke="#2c2218"
              strokeWidth="0.9"
              opacity="0.55"
            />
            <line
              x1="0"
              y1="-52"
              x2="0"
              y2="52"
              stroke="#2c2218"
              strokeWidth="0.9"
              opacity="0.55"
            />
            <path d="M 0 -50 L 7 -14 L 0 -6 L -7 -14 Z" fill="#a5301b" />
            <text
              className="a-lbl"
              x="0"
              y="-58"
              textAnchor="middle"
              style={{ fontSize: 14, fill: '#a5301b' }}
            >
              N
            </text>
          </g>

          {/* the open-water label lives where the folio would otherwise cover
              it, so it is a home-plate flourish only */}
          {home && (
            <text className="a-lbl a-lbl-sea" x="320" y="640" textAnchor="middle">
              Mare Incognitum
            </text>
          )}
          <text
            className="a-lbl a-lbl-region"
            x={plate.regions.north.x}
            y={plate.regions.north.y}
            textAnchor="middle"
          >
            EDUCATION
          </text>
          <text
            className="a-lbl a-lbl-region"
            x={plate.regions.south.x}
            y={plate.regions.south.y}
            textAnchor="middle"
          >
            EXPERIENCE
          </text>
          <text className="a-lbl a-lbl-terra" x="880" y="232" textAnchor="middle">
            Terra Incognita
          </text>
          {/* map lettering stays terse; the full plan is set in the CV folio */}
          <text className="a-lbl a-lbl-tiny" x="880" y="254" textAnchor="middle">
            — reported, not yet surveyed —
          </text>

          <g className="a-lbl a-lbl-city">
            {plate.settlements.map((s) => (
              <g key={s.name}>
                <circle cx={s.at.x} cy={s.at.y} r={s.major ? 3.2 : 2.4} fill="#2c2218" />
                <text x={s.at.x + 11} y={s.at.y + 5} style={{ fontSize: s.major ? 14.5 : 12 }}>
                  {s.name}
                </text>
              </g>
            ))}
          </g>

          <g className="a-lbl a-lbl-tiny">
            {plate.isles.map(({ t, project, label }) => (
              <text key={t.id} x={label.x} y={label.y} textAnchor="middle">
                {project.title}
              </text>
            ))}
          </g>
        </svg>

        <div className="a-neatline" />

        <nav className="a-index" aria-label="Charts">
          <p className="a-index-tag">CHARTS</p>
          {TOP_LEVEL_ROUTES.map((r) => (
            <Link key={r.path} to={r.path} navigate={navigate} current={path === r.path}>
              {r.label}
            </Link>
          ))}
        </nav>

        {home ? (
          <Cartouche content={content} />
        ) : (
          <div className="a-folio a-ink-in" key={path}>
            {route.kind === 'cv' && <Cv content={content} navigate={navigate} />}
            {route.kind === 'projects' && <Projects content={content} navigate={navigate} />}
            {route.kind === 'project' && (
              <ProjectSheet content={content} slug={route.slug} navigate={navigate} />
            )}
            {route.kind === 'interests' && <Interests content={content} />}
            {route.kind === 'notFound' && <NotFound path={path} navigate={navigate} />}
          </div>
        )}

        {home && <Legend content={content} />}

        {home && content.announcements.length > 0 && (
          <Link to="/projects" navigate={navigate} className="a-ticker">
            <b>IN PREPARATION</b> {content.announcements.map((a) => a.title).join(' · ')}
          </Link>
        )}
      </div>

      <svg className="a-grain" aria-hidden="true">
        <filter id="a-grainF">
          <feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves="4" seed="12" />
          <feColorMatrix type="saturate" values="0" />
        </filter>
        <rect width="100%" height="100%" filter="url(#a-grainF)" opacity="0.2" />
      </svg>
    </div>
  )
}

function Cartouche({ content }: { content: SiteContent }) {
  return (
    <section className="a-cartouche a-ink-in">
      <p className="a-eyebrow">TABULA I</p>
      <h1 className="a-title">
        Damyan Hristov
        <em>his territories, described</em>
      </h1>
      <p className="a-lede">
        <span className="a-drop">G</span>ames, engines and experimental graphics. Herein the
        provinces of study and of labour, the isles of work already shipped, and — ruled in red, for
        it rests on report rather than survey — the coast toward Delft.
      </p>
      <div className="a-socials">
        {content.profile.socials.map((s) => (
          <a key={s.url} href={s.url}>
            {s.label}
          </a>
        ))}
      </div>
      <p className="a-imprint">Eindhoven · MMXXVI</p>
    </section>
  )
}

function Legend({ content }: { content: SiteContent }) {
  const { proficiencies } = content.cv
  return (
    <aside className="a-legend a-ink-in">
      <h2>EXPLANATIO</h2>
      <div className="a-legend-row">
        <svg width="42" height="15">
          <rect width="42" height="15" fill="url(#a-hLight)" stroke="#2c2218" strokeWidth="0.8" />
        </svg>
        <span>Provinces of study &amp; of labour</span>
      </div>
      <div className="a-legend-row">
        <svg width="42" height="15">
          <rect width="42" height="15" fill="url(#a-hMed)" stroke="#2c2218" strokeWidth="0.8" />
        </svg>
        <span>Isles of shipped work</span>
      </div>
      <div className="a-legend-row">
        <svg width="42" height="15">
          <rect width="42" height="15" fill="url(#a-hCross)" stroke="#2c2218" strokeWidth="0.8" />
        </svg>
        <span>Isles of university making</span>
      </div>
      <div className="a-legend-row">
        <svg width="42" height="15">
          <line
            x1="0"
            y1="8"
            x2="42"
            y2="8"
            stroke="#a5301b"
            strokeWidth="1.6"
            strokeDasharray="7 5"
          />
        </svg>
        <span>Reported, unsurveyed — the Delft passage</span>
      </div>
      <div className="a-legend-row">
        <svg width="42" height="15">
          <line
            x1="0"
            y1="8"
            x2="42"
            y2="8"
            stroke="#a5301b"
            strokeWidth="1"
            strokeDasharray="4 5"
          />
        </svg>
        <span>Routes: a tongue to the work that proves it</span>
      </div>
      <p className="a-legend-note">
        {proficiencies.spoken.map((s) => `${s.language} (${s.level})`).join(' · ')}.{' '}
        {proficiencies.programming.map((p) => p.name).join(' · ')};{' '}
        {proficiencies.expanding.map((p) => p.name).join(' · ')} in the learning.
      </p>
    </aside>
  )
}

function Cv({ content, navigate }: { content: SiteContent; navigate: ThemeProps['navigate'] }) {
  const { cv } = content
  return (
    <>
      <h1>The Provinces</h1>
      <p className="a-folio-sub">a description of study and of labour</p>

      <h2 className="a-h2">EDUCATION</h2>
      {cv.education.map((e) => (
        <article className="a-entry" key={e.school}>
          <h3>{e.program}</h3>
          <p className="a-meta">
            {e.school} · {e.location} · {e.start} to {e.end}
          </p>
          <ul>
            {e.details.map((d) => (
              <li key={d}>{d}</li>
            ))}
          </ul>
        </article>
      ))}

      <h2 className="a-h2">EXPERIENCE</h2>
      {cv.experience.map((e) => (
        <article className="a-entry" key={e.company}>
          <h3>
            {e.role} · {e.company}
          </h3>
          <p className="a-meta">
            {e.start} to {e.end}
            {e.teamSize ? ` · team of ~${e.teamSize}` : ''}
            {e.tools.length > 0 ? ` · ${e.tools.join(', ')}` : ''}
          </p>
          <p>{e.summary}</p>
          <ul>
            {e.highlights.map((h) => (
              <li key={h}>{h}</li>
            ))}
          </ul>
          {e.links.map((l) => (
            <a className="a-out" key={l.url} href={l.url}>
              {l.label}
            </a>
          ))}
        </article>
      ))}

      <h2 className="a-h2">TERRA INCOGNITA</h2>
      <p className="a-prose">{cv.plans}</p>

      <h2 className="a-h2">PROFICIENCIES</h2>
      <p className="a-prose">
        {cv.proficiencies.spoken.map((s) => `${s.language} (${s.level})`).join(' · ')}
      </p>
      {[...cv.proficiencies.programming, ...cv.proficiencies.expanding].map((p) => (
        <article className="a-entry" key={p.name}>
          <h3>{p.name}</h3>
          <p>{p.evidence}</p>
          <p className="a-meta">
            charted by:{' '}
            {p.projectSlugs.map((slug, i) => (
              <span key={slug}>
                {i > 0 && ' · '}
                <Link to={`/projects/${slug}`} navigate={navigate}>
                  {content.projects.find((pr) => pr.slug === slug)?.title ?? slug}
                </Link>
              </span>
            ))}
          </p>
        </article>
      ))}
    </>
  )
}

const CHIP: Record<Project['category'], string> = {
  personal: 'PERSONAL',
  jam: 'GAME JAM',
  university: 'UNIVERSITY',
}

function Projects({
  content,
  navigate,
}: {
  content: SiteContent
  navigate: ThemeProps['navigate']
}) {
  const released = content.projects.filter((p) => p.status === 'released')
  return (
    <>
      <h1>The Archipelago</h1>
      <p className="a-folio-sub">isles of work already shipped</p>

      {content.announcements.length > 0 && (
        <>
          <h2 className="a-h2">IN PREPARATION</h2>
          {content.announcements.map((a) => (
            <article className="a-entry" key={a.id}>
              <h3>{a.title}</h3>
              <p>{a.body}</p>
            </article>
          ))}
        </>
      )}

      <h2 className="a-h2">SURVEYED</h2>
      <div className="a-roll">
        {released.map((p, i) => (
          <Link key={p.slug} to={`/projects/${p.slug}`} navigate={navigate}>
            <span className="a-roll-no">
              ISLE {String(i + 1).padStart(2, '0')} · {CHIP[p.category]}
            </span>
            <span className="a-roll-title">{p.title}</span>
            <span className="a-roll-sum">{p.summary}</span>
          </Link>
        ))}
      </div>
    </>
  )
}

function ProjectSheet({
  content,
  slug,
  navigate,
}: {
  content: SiteContent
  slug: string
  navigate: ThemeProps['navigate']
}) {
  const project = content.projects.find((p) => p.slug === slug)
  if (!project) return <NotFound path={`/projects/${slug}`} navigate={navigate} />
  const facts: [string, string][] = []
  if (project.year) facts.push(['Year', String(project.year)])
  if (project.event) facts.push(['Where', project.event])
  if (project.role) facts.push(['Role', project.role])
  if (project.duration) facts.push(['Duration', project.duration])
  if (project.team?.size) facts.push(['Team', `${project.team.size} people`])
  if (project.tools.length > 0) facts.push(['Tools', project.tools.join(', ')])
  return (
    <>
      <Link to="/projects" navigate={navigate} className="a-back">
        ← back to the archipelago
      </Link>
      <h1>{project.title}</h1>
      <p className="a-folio-sub">{CHIP[project.category].toLowerCase()}</p>
      <dl className="a-facts">
        {facts.map(([k, v]) => (
          <div key={k}>
            <dt>{k}</dt>
            <dd>{v}</dd>
          </div>
        ))}
      </dl>
      <p className="a-prose">{project.summary}</p>
      {project.team?.members && <p className="a-meta">with {project.team.members.join(', ')}</p>}
      <div className="a-actions">
        {project.links.map((l) => (
          <a key={l.url} href={l.url} className="a-btn">
            {l.label}
          </a>
        ))}
        {project.links.length === 0 && <p className="a-meta">links land here once it ships</p>}
      </div>
    </>
  )
}

function Interests({ content }: { content: SiteContent }) {
  return (
    <>
      <h1>Marginalia</h1>
      <p className="a-folio-sub">what fills the borders of the plate</p>
      {content.interests.map((section) => (
        <article className="a-entry" key={section.id}>
          <h3>{section.title}</h3>
          <p>{section.body}</p>
          {section.links.map((l) => (
            <a className="a-out" key={l.url} href={l.url}>
              {l.label}
            </a>
          ))}
        </article>
      ))}
    </>
  )
}

function NotFound({ path, navigate }: { path: string; navigate: ThemeProps['navigate'] }) {
  return (
    <>
      <h1>Off the Plate</h1>
      <p className="a-folio-sub">no such territory was surveyed</p>
      <p className="a-prose">
        <code>{path}</code> lies beyond the neatline.
      </p>
      <div className="a-actions">
        <Link to="/" navigate={navigate} className="a-btn">
          RETURN TO THE CHART
        </Link>
      </div>
    </>
  )
}
