// atlas — procedural cartography.
//
// Coastlines are the canonical fractal (Mandelbrot, "How Long Is the Coast of
// Britain?"), so this theme shares the site's DNA with julia and singularity and
// simply wears 1662. Landmasses are generated by midpoint displacement seeded
// from content, which means every territory keeps a stable identity across
// reloads the same way a project keeps its Julia constant.
//
// Everything here is pure and deterministic: same seed in, same coast out.

export interface Pt {
  x: number
  y: number
}

/** mulberry32 — compact, well-distributed, seedable. */
export function mulberry32(seed: number): () => number {
  let s = seed >>> 0
  return () => {
    s = (s + 0x6d2b79f5) >>> 0
    let t = Math.imul(s ^ (s >>> 15), 1 | s)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

export function hashString(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0
  return Math.abs(h)
}

/** Coarse control polygon: an ellipse with per-vertex radius and angle jitter. */
export function baseBlob(
  cx: number,
  cy: number,
  rx: number,
  ry: number,
  n: number,
  rng: () => number,
  jitter = 0.3,
): Pt[] {
  const pts: Pt[] = []
  for (let i = 0; i < n; i++) {
    const frac = i / n
    // angle jitter stays below half a step so vertices can never reorder
    const a = frac * Math.PI * 2 + (rng() - 0.5) * ((Math.PI * 2) / n) * 0.55
    const r = 1 + (rng() - 0.5) * 2 * jitter
    pts.push({ x: cx + Math.cos(a) * rx * r, y: cy + Math.sin(a) * ry * r })
  }
  return pts
}

const dist = (a: Pt, b: Pt) => Math.hypot(b.x - a.x, b.y - a.y)

/**
 * Midpoint displacement. Each pass inserts a midpoint per edge and pushes it
 * along the edge normal. Displacement is proportional to edge length, so detail
 * is self-similar across scales; `persistence` tunes the Hurst exponent —
 * higher is craggier. Displacement is clamped against the shorter adjacent edge,
 * which is what stops the outline folding through itself at high roughness.
 */
export function displace(
  points: Pt[],
  rng: () => number,
  roughness = 0.28,
  iterations = 5,
  persistence = 0.92,
): Pt[] {
  let cur = points
  let amp = roughness
  for (let it = 0; it < iterations; it++) {
    const next: Pt[] = []
    for (let i = 0; i < cur.length; i++) {
      const a = cur[i]
      const b = cur[(i + 1) % cur.length]
      const prev = cur[(i - 1 + cur.length) % cur.length]
      const after = cur[(i + 2) % cur.length]
      next.push(a)

      const dx = b.x - a.x
      const dy = b.y - a.y
      const len = Math.hypot(dx, dy)
      if (len < 1e-6) continue

      // never displace further than a third of the tightest neighbouring
      // feature. This is a *local* guard: it cannot see a far-away segment
      // across a narrow neck, so territory() still validates the whole outline.
      const cap = 0.34 * Math.min(len, dist(prev, a), dist(b, after))
      let disp = (rng() - 0.5) * len * amp
      disp = Math.max(-cap, Math.min(cap, disp))

      next.push({
        x: (a.x + b.x) / 2 + (-dy / len) * disp,
        y: (a.y + b.y) / 2 + (dx / len) * disp,
      })
    }
    cur = next
    amp *= persistence
  }
  return cur
}

/** Open fractal polyline between two anchors — used for internal borders. */
export function fractalLine(
  a: Pt,
  b: Pt,
  rng: () => number,
  roughness = 0.16,
  iterations = 5,
): Pt[] {
  let cur: Pt[] = [a, b]
  let amp = roughness
  for (let it = 0; it < iterations; it++) {
    const next: Pt[] = []
    for (let i = 0; i < cur.length - 1; i++) {
      const p = cur[i]
      const q = cur[i + 1]
      next.push(p)
      const dx = q.x - p.x
      const dy = q.y - p.y
      const len = Math.hypot(dx, dy)
      if (len < 1e-6) continue
      const disp = (rng() - 0.5) * len * amp
      next.push({
        x: (p.x + q.x) / 2 + (-dy / len) * disp,
        y: (p.y + q.y) / 2 + (dx / len) * disp,
      })
    }
    next.push(cur[cur.length - 1])
    cur = next
    amp *= 0.9
  }
  return cur
}

/**
 * Catmull-Rom → cubic Bézier. Engraved coasts are drawn with a burin, not
 * plotted, so the polyline is smoothed into curves; with this many sample
 * points the smoothing reads as tooling rather than as lost detail.
 */
export function toPath(pts: Pt[], closed = true, tension = 6): string {
  if (pts.length < 2) return ''
  const n = pts.length
  const at = (i: number): Pt => (closed ? pts[(i + n) % n] : pts[Math.max(0, Math.min(n - 1, i))])

  let d = `M ${pts[0].x.toFixed(2)} ${pts[0].y.toFixed(2)}`
  const last = closed ? n : n - 1
  for (let i = 0; i < last; i++) {
    const p0 = at(i - 1)
    const p1 = at(i)
    const p2 = at(i + 1)
    const p3 = at(i + 2)
    const c1x = p1.x + (p2.x - p0.x) / tension
    const c1y = p1.y + (p2.y - p0.y) / tension
    const c2x = p2.x - (p3.x - p1.x) / tension
    const c2y = p2.y - (p3.y - p1.y) / tension
    d += ` C ${c1x.toFixed(2)} ${c1y.toFixed(2)}, ${c2x.toFixed(2)} ${c2y.toFixed(2)}, ${p2.x.toFixed(2)} ${p2.y.toFixed(2)}`
  }
  return closed ? `${d} Z` : d
}

// --- geometry helpers, also used by the tests -------------------------------

export function area(pts: Pt[]): number {
  let a = 0
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i]
    const q = pts[(i + 1) % pts.length]
    a += p.x * q.y - q.x * p.y
  }
  return Math.abs(a) / 2
}

export function perimeter(pts: Pt[]): number {
  let l = 0
  for (let i = 0; i < pts.length; i++) l += dist(pts[i], pts[(i + 1) % pts.length])
  return l
}

export function bbox(pts: Pt[]): { minX: number; minY: number; maxX: number; maxY: number } {
  return pts.reduce(
    (acc, p) => ({
      minX: Math.min(acc.minX, p.x),
      minY: Math.min(acc.minY, p.y),
      maxX: Math.max(acc.maxX, p.x),
      maxY: Math.max(acc.maxY, p.y),
    }),
    { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity },
  )
}

function segmentsCross(a: Pt, b: Pt, c: Pt, d: Pt): boolean {
  const o = (p: Pt, q: Pt, r: Pt) =>
    Math.sign((q.x - p.x) * (r.y - p.y) - (q.y - p.y) * (r.x - p.x))
  const o1 = o(a, b, c)
  const o2 = o(a, b, d)
  const o3 = o(c, d, a)
  const o4 = o(c, d, b)
  return o1 !== o2 && o3 !== o4
}

/** True when the closed outline never crosses itself — a coast, not a knot. */
export function isSimplePolygon(pts: Pt[]): boolean {
  const n = pts.length
  for (let i = 0; i < n; i++) {
    for (let j = i + 2; j < n; j++) {
      // skip the pair that shares the wrap-around vertex
      if (i === 0 && j === n - 1) continue
      if (segmentsCross(pts[i], pts[(i + 1) % n], pts[j], pts[(j + 1) % n])) return false
    }
  }
  return true
}

// --- territories -------------------------------------------------------------

export interface Territory {
  id: string
  points: Pt[]
  path: string
}

export interface LandSpec {
  id: string
  cx: number
  cy: number
  rx: number
  ry: number
  /** control-polygon vertices; more = a busier base silhouette */
  n?: number
  roughness?: number
  iterations?: number
  persistence?: number
  seed?: number
}

/**
 * Build one territory. Composition (where a landmass sits, how big it is) stays
 * an authored decision — cartographic layout is design, not noise — while the
 * silhouette is generated, so shapes are organic but the plate stays balanced.
 *
 * The local displacement cap prevents most folds but not all: a coast can still
 * cross itself where displacement carries one lobe into a distant one. Rather
 * than accept a knot, generate → verify → retry at lower roughness, and fall
 * back to the control polygon, which is star-shaped about its centre and so
 * provably simple. A generated map must never render a broken outline.
 */
export function territory(spec: LandSpec): Territory {
  const seed = spec.seed ?? hashString(spec.id)
  const n = spec.n ?? 9
  const build = (roughness: number) => {
    const rng = mulberry32(seed)
    const base = baseBlob(spec.cx, spec.cy, spec.rx, spec.ry, n, rng, 0.28)
    return {
      base,
      points: displace(base, rng, roughness, spec.iterations ?? 5, spec.persistence ?? 1),
    }
  }

  let roughness = spec.roughness ?? 0.36
  let base = build(roughness).base
  for (let attempt = 0; attempt < 5; attempt++) {
    const built = build(roughness)
    base = built.base
    if (isSimplePolygon(built.points)) {
      return { id: spec.id, points: built.points, path: toPath(built.points) }
    }
    roughness *= 0.72
  }
  return { id: spec.id, points: base, path: toPath(base) }
}

/** Relief hachures: short downslope ticks scattered inside a territory. */
export function hachures(
  t: Territory,
  rng: () => number,
  count: number,
  length = 22,
): { x1: number; y1: number; x2: number; y2: number }[] {
  const box = bbox(t.points)
  const out: { x1: number; y1: number; x2: number; y2: number }[] = []
  let guard = 0
  while (out.length < count && guard++ < count * 40) {
    const x = box.minX + rng() * (box.maxX - box.minX)
    const y = box.minY + rng() * (box.maxY - box.minY)
    if (!pointInPolygon({ x, y }, t.points)) continue
    const l = length * (0.55 + rng() * 0.75)
    out.push({ x1: x, y1: y, x2: x, y2: y + l })
  }
  return out
}

export function pointInPolygon(p: Pt, poly: Pt[]): boolean {
  let inside = false
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const a = poly[i]
    const b = poly[j]
    if (a.y > p.y !== b.y > p.y && p.x < ((b.x - a.x) * (p.y - a.y)) / (b.y - a.y) + a.x) {
      inside = !inside
    }
  }
  return inside
}
